FROM ubuntu:xenial

COPY cloudera.list /etc/apt/sources.list.d/cloudera.list
COPY kudu_master_command.sh /kudu_master_command.sh
COPY archive.key /root/archive.key

RUN apt-key add /root/archive.key && apt-get update && apt-get install -y kudu kudu-master 
RUN echo "--use-hybrid-clock=false" >> /etc/kudu/conf/master.gflagfile && echo "--use-hybrid-clock=false" >> /etc/kudu/conf/tserver.gflagfile

CMD ["/kudu_master_command.sh"]
