version: '3'

services:
  master:
    build:
      dockerfile: Dockerfile_ubuntu_master
      context: .
    image: kudu_master_ubuntu
    stdin_open: true
    tty: true
    networks:
      - hf_dev_network
    ports:
      - "18051-18053:8051"

  tserver:
    build:
      dockerfile: Dockerfile_ubuntu_tserver
      context: .
    image: kudu_tserver_ubuntu
    stdin_open: true
    tty: true
    networks:
      - hf_dev_network
    ports:
      - "17050-17052:8050"

networks:
  dev_network:
    external: true

