FROM ubuntu:xenial

COPY cloudera.list /etc/apt/sources.list.d/cloudera.list
COPY command.sh /command.sh
COPY archive.key /root/archive.key

RUN apt-key add /root/archive.key && apt-get update && apt-get install -y kudu kudu-master kudu-tserver libkuduclient0 libkuduclient-dev

CMD ["/command.sh"]
