FROM centos:7
ENV container docker

COPY cloudera-kudu.repo /etc/yum.repos.d/cloudera-kudu.repo
COPY kudu_master_command.sh /kudu_master_command.sh

RUN yum install -y initscripts kudu kudu-master 
RUN echo "--use-hybrid-clock=false" >> /etc/kudu/conf/master.gflagfile

CMD ["/kudu_master_command.sh"]
