FROM centos:7
ENV container docker

COPY cloudera-kudu.repo /etc/yum.repos.d/cloudera-kudu.repo
COPY kudu_tserver_command.sh /kudu_tserver_command.sh

RUN yum install -y initscripts kudu kudu-tserver
RUN echo "--use-hybrid-clock=false" >> /etc/kudu/conf/tserver.gflagfile && echo "--tserver_master_addrs=master:7051" >> /etc/kudu/conf/tserver.gflagfile 

CMD ["/kudu_tserver_command.sh"]
